# -*- coding: utf-8 -*-
"""1573-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12SFNPhZgA2X-fcmpH1GqD9M4S51ezYcd
"""

from google.colab import files
upload = files.upload()

f=open('code.txt',"r")
txt =f.read()
print(txt)

copy = open("output.txt", "w")
with open('code.txt',"r") as f:
   for line in f:
     line = line.split('/',1 )[0]
     copy.write(line)
     copy.write("\n")
copy=open("output.txt","r")
with open("output.txt","r") as f:
    lines=f.readlines()
with open("output.txt","w") as f:  
    for line in lines:
       if line.strip():
          f.write(line)
          print(line)