# -*- coding: utf-8 -*-
"""1573_5_A2-identifier_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNMYu9gUBQvuCN4bOq2eTjprfgv7wHZj
"""

import re
import pandas as pd
from collections import Counter
f = open("input.c", "r")
text = f.read()
print(text)

keywords = ['printf','main','auto','break', 'case', 'char', 'const', 'continue', 'default', 'do', 
			'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if', 
			'int', 'long', 'register', 'return', 'short', 'signed', 'sizeof', 'static', 
			'struct', 'switch', 'typedef', 'union', 'unsigned', 'void', 'volatile', 'while']
symbols = ['!', '@', '$', '%', '&', '^', '*']
oparators = ['+', '-', '*', '/', '=', '+=', '-=', '==', '<', '>', '<=', '>=']
headerfile = ['#', 'include', '.h']
delimiters = [' ', '	', ',', '\n', ';', '(', ')', '<', '>', '{', '}', '[', ']']
built_in_functon= []


in_keywords = []
in_spl_symbols = []
in_oparators = []
in_delimiters = []
in_identifiers = []
in_constants = []
in_headerfile = []
in_built_in_functon = []
tokens = []
isStr = False
isWord = False
isCmt = 0
token = ''

for i in text:
	if i == '/':
		isCmt = isCmt+1

	elif isCmt == 2:
		if i == '\n':
			token = ''
			isCmt = 0
	
	elif i == '"' or i == "'":
		if isStr:
			tokens.append(token)
			token = ''
		isStr = not isStr 

	elif isStr:
		token = token+i
    
	elif i in symbols:
		tokens.append(i)
           
	elif i.isalnum() and not isWord:
		isWord = True
		token = i
    
	elif (i in delimiters) or (i in oparators):
		if token:
			tokens.append(token)
			token = ''
        
		if not (i==' ' or i=='\n' or i=='	'):
			tokens.append(i)

	elif isWord:
		token = token+i


for token in tokens:
	if token in symbols:
		in_spl_symbols.append(token)

	elif token in oparators:
		in_oparators.append(token)

	elif token in keywords:
		in_keywords.append(token)
	
	elif token in headerfile:
		in_headerfile.append(token)
  
	elif token in built_in_functon:
		in_built_in_functon.append(token)
				
	elif re.search("^[_a-zA-Z][_a-zA-Z0-9]*$",token):
		in_identifiers.append(token)
		
	elif token in delimiters:
		in_delimiters.append(token)
		
	else:
		in_constants.append(token)
		
f.close()

print("\nNo. of Identifiers = ",len(in_identifiers))
identifier = Counter(in_identifiers)
print('\n')
print(pd.DataFrame(identifier.items(), columns=['Identifier', 'Value']))